import {useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,Boxes,Users,ShieldCheck,Workflow,Plug,ScrollText,RefreshCw,ArrowUpRight,AlertTriangle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {api,type Identity} from './api';
import {HostedPanel} from './hosted';
import './admin.css';

type Lifecycle={support_contact:string;review_due:number;profile:string;queries_per_minute:number;min_refresh_seconds:number;revision:number};
type AppRow={id:string;name:string;owner:string;classification:string;enabled:boolean;runtime_admitted:boolean;active_version:string|null;latest_status:string;findings:string[];lifecycle:Lifecycle|null;requests_this_minute:number;can_share:boolean};
type Account={id:string;email:string;name:string;role:string;groups:string[];enabled:boolean};
type PackageRule={ecosystem:string;name:string;version:string;integrity:string;source:string;approved:boolean};
type Job={id:string;app_id:string;kind:string;status:string;attempts:number;detail:string|null;created:number;lease_until:number|null};
type Overview={apps:AppRow[];external_apps:{id:string;name:string;owner:string;version:string|null}[];jobs:Job[];audit:{id:number;action:string;actor:string;resource:string;created:number;details:Record<string,unknown>}[];connections:{id:string;state:string;acceptance:string;configuration_present:Record<string,boolean>}[];demo:boolean;pending_audit_delivery:number;notes:string[]};
type Confirmation={title:string;description:string;path:string;method:string;body?:unknown;reason?:boolean};
const sections=[['overview','Overview',Activity],['apps','Applications',Boxes],['people','People & access',Users],['packages','Package policy',ShieldCheck],['workers','Worker jobs',Workflow],['connections','Connections',Plug],['audit','Audit history',ScrollText]] as const;
const date=(value:number)=>new Date(value*1000).toLocaleString();

export default function AdminConsole({user,onChange}:{user:Identity;onChange:()=>Promise<void>}){
 const [data,setData]=useState<Overview|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[packages,setPackages]=useState<PackageRule[]>([]);
 const [section,setSection]=useState('overview'),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loadedAt,setLoadedAt]=useState<number|null>(null);
 const [app,setApp]=useState<AppRow|null>(null),[policyApp,setPolicyApp]=useState<AppRow|null>(null),[person,setPerson]=useState<Account|null>(null),[newPackage,setNewPackage]=useState(false),[confirmation,setConfirmation]=useState<Confirmation|null>(null),[reason,setReason]=useState('');
 const refresh=useCallback(async()=>{
  const [overview,people,rules]=await Promise.all([api<Overview>('/v2/admin/overview'),api<Account[]>('/admin/users'),api<PackageRule[]>('/v2/runtime-packages')]);
  setData(overview);setAccounts(people);setPackages(rules);setLoadedAt(Date.now());
 },[]);
 useEffect(()=>{let current=true;Promise.all([api<Overview>('/v2/admin/overview'),api<Account[]>('/admin/users'),api<PackageRule[]>('/v2/runtime-packages')]).then(([overview,people,rules])=>{if(current){setData(overview);setAccounts(people);setPackages(rules);setLoadedAt(Date.now())}}).catch(e=>{if(current)setError(e.message)});return()=>{current=false}},[]);
 async function mutate(path:string,method:string,body?:unknown){setBusy(true);setError('');try{await api(path,method,body);await refresh();await onChange();return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 function confirm(value:Confirmation){setReason('');setConfirmation(value)}
 const apps=useMemo(()=>data?.apps.filter(a=>`${a.name} ${a.owner} ${a.classification}`.toLowerCase().includes(search.toLowerCase()))??[],[data,search]);
 const blocked=data?.apps.filter(a=>a.enabled&&a.findings.length>0)??[];
 const waiting=data?.jobs.filter(j=>['queued','leased','dead_letter','failed'].includes(j.status))??[];
 if(user.role!=='admin')return null;
 return <section className="admin-console" aria-label="Administration console">
  <div className="admin-heading"><div><p className="admin-eyebrow">WORKSPACE ADMINISTRATION</p><h1>Mission control</h1><p>Operate the platform. Keep access intentional.</p></div><div className="admin-heading-actions"><span className="admin-env">{data?.demo?'Synthetic environment':'Work environment'}</span><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><RefreshCw size={15}/> Refresh</Button><small>{loadedAt?'Updated '+new Date(loadedAt).toLocaleTimeString():'Loading records…'}</small></div></div>
  {error&&<p className="form-error" role="alert">{error}</p>}
  {!data?<div className="admin-empty">{error?'Records could not be loaded. Retry with Refresh.':'Loading workspace records…'}</div>:<Tabs value={section} onValueChange={s=>{setSection(s);setSearch('')}} className="admin-layout">
   <TabsList className="admin-nav" aria-label="Admin sections">{sections.map(([id,label,Icon])=><TabsTrigger value={id} key={id}><Icon size={17}/>{label}</TabsTrigger>)}</TabsList>
   <div className="admin-workspace">
    <TabsContent value="overview">
     <div className="admin-kpis"><Kpi label="Registered apps" value={data.apps.length+data.external_apps.length} note={`${data.apps.length} hosted · ${data.external_apps.length} links / demos`}/><Kpi label="Needs attention" value={blocked.length} note="Hosted apps with release blockers"/><Kpi label="Worker queue" value={waiting.length} note="Queued, running, or needing recovery"/><Kpi label="Enabled people" value={accounts.filter(a=>a.enabled).length} note="Membership is explicitly provisioned"/></div>
     <div className="admin-overview-grid"><section className="admin-surface"><h2>Release readiness</h2><p className="admin-muted">Current policy is checked again at launch and query time.</p>{blocked.length?blocked.slice(0,6).map(a=><button className="admin-attention" key={a.id} onClick={()=>setApp(a)}><AlertTriangle size={18}/><span><strong>{a.name}</strong><small>{a.findings[0]}</small></span><ArrowUpRight size={16}/></button>):<div className="admin-empty">No release blockers among visible hosted apps. Unconnected integrations still require acceptance testing.</div>}<Button variant="outline" onClick={()=>setSection('apps')}>View applications</Button></section><section className="admin-surface"><h2>Production connection checklist</h2><p className="admin-muted">Environment variables are not proof of a successful connection.</p>{data.connections.slice(0,5).map(c=><div className="admin-check" key={c.id}><span>{c.id.replaceAll('-',' ')}</span><Status value="Unverified"/></div>)}<Button variant="outline" onClick={()=>setSection('connections')}>Inspect all connections</Button></section></div>
     <div className="admin-boundary"><ShieldCheck size={20}/><p>Administrator access does not grant warehouse access. Restricted applications are omitted unless you have explicit app permissions.</p></div>
    </TabsContent>
    <TabsContent value="apps"><PanelTitle title="Applications" description="Ownership, release health, review deadlines, and access controls."/><Input aria-label="Search managed applications" placeholder="Search name, owner, or classification" value={search} onChange={e=>setSearch(e.target.value)}/>
     <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Application</th><th>Release</th><th>Review / profile</th><th>Queries / min</th><th>Controls</th></tr></thead><tbody>{apps.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.owner} · {a.classification}</small></td><td><Status value={!a.enabled?'Suspended':a.findings.length?'Blocked':a.runtime_admitted?'Active':'Awaiting promotion'}/><small>{a.active_version?'v'+a.active_version:a.latest_status}</small></td><td>{a.lifecycle?<><span>{new Date(a.lifecycle.review_due*1000).toLocaleDateString()}</span><small>{a.lifecycle.profile}</small></>:<span>Not recorded</span>}</td><td>{a.requests_this_minute}<small>Limit {a.lifecycle?.queries_per_minute??120}</small></td><td><div className="admin-actions"><Button variant="outline" onClick={()=>setApp(a)}>Manage</Button><Button variant="outline" disabled={!a.can_share} onClick={()=>setPolicyApp(a)}>Lifecycle</Button><Button variant="outline" disabled={!a.can_share||busy} onClick={()=>confirm({title:a.enabled?'Suspend this app?':'Resume this app?',description:a.enabled?'New requests will be denied. The production deployment adapter must also stop or restrict the underlying service.':'Current release and data policies still apply. A new admitted deployment may be necessary.',path:`/v2/apps/${a.id}/${a.enabled?'suspend':'resume'}`,method:'POST'})}>{a.enabled?'Suspend':'Resume'}</Button></div></td></tr>)}</tbody></table></div>{!apps.length&&<div className="admin-empty">No visible hosted apps. Register a containerized app from the gallery, then upload its source.</div>}
     <h3 className="admin-subheading">External links & built-in demonstrations</h3><p className="admin-muted">Registration does not make external hosting subject to container controls.</p><div className="admin-linked-apps">{data.external_apps.filter(a=>a.name.toLowerCase().includes(search.toLowerCase())).map(a=><article key={a.id}><strong>{a.name}</strong><small>{a.owner} · {a.version?'v'+a.version:'Private draft'}</small></article>)}</div>
    </TabsContent>
    <TabsContent value="people"><PanelTitle title="People & access" description="Edit roles and memberships. Changes revoke existing sessions; identity-provider provisioning remains separate."/><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Person</th><th>Role</th><th>Groups</th><th>Status</th><th>Action</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.email}</small></td><td>{a.role}</td><td>{a.groups.join(', ')||'No groups'}</td><td><Status value={a.enabled?'Enabled':'Disabled'}/></td><td><Button variant="outline" onClick={()=>setPerson(a)}>Edit access</Button></td></tr>)}</tbody></table></div></TabsContent>
    <TabsContent value="packages"><PanelTitle title="Container package policy" description="Exact versions and integrity hashes. Revoking a dependency blocks affected releases on their next policy check."/><Button variant="outline" onClick={()=>setNewPackage(true)}>Add exact package rule</Button><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Dependency</th><th>Source / integrity</th><th>Policy</th><th>Action</th></tr></thead><tbody>{packages.map(p=><tr key={`${p.ecosystem}:${p.name}:${p.version}:${p.integrity}`}><td><strong>{p.name}@{p.version}</strong><small>{p.ecosystem}</small></td><td><span className="admin-wrap">{p.source}</span><small className="admin-wrap">{p.integrity}</small></td><td><Status value={p.approved?'Approved':'Revoked'}/></td><td><Button variant="outline" disabled={busy} onClick={()=>confirm({title:p.approved?'Revoke this dependency?':'Approve this exact dependency?',description:p.approved?'Affected apps can stop serving on their next request. Inspect dependencies in each app release before confirming.':'Only approve a complete, independently verified inventory entry. This action is not a vulnerability scan.',path:'/v2/runtime-packages',method:'PUT',body:{...p,approved:!p.approved}})}>{p.approved?'Revoke':'Approve'}</Button></td></tr>)}</tbody></table></div>{!packages.length&&<div className="admin-empty">No hosted-runtime package rules exist yet. Unapproved dependencies block admission.</div>}</TabsContent>
    <TabsContent value="workers"><PanelTitle title="Worker jobs" description="Renewable leases and explicit recovery. Cancelling here invalidates reports; the worker must clean up its external task."/><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Job</th><th>App</th><th>Status</th><th>Attempts / lease</th><th>Recovery</th></tr></thead><tbody>{data.jobs.map(j=><tr key={j.id}><td><strong>{j.kind}</strong><small>{j.id.slice(0,12)}</small></td><td>{data.apps.find(a=>a.id===j.app_id)?.name}</td><td><Status value={j.status}/><small>{j.detail}</small></td><td>{j.attempts} / 3<small>{j.lease_until?date(j.lease_until):'No active lease'}</small></td><td>{['queued','leased'].includes(j.status)?<Button variant="outline" disabled={busy} onClick={()=>confirm({title:'Cancel this job?',description:'Stale worker reports will be rejected. This does not itself terminate a cloud build or container.',path:`/v2/admin/jobs/${j.id}/action`,method:'POST',body:{action:'cancel'},reason:true})}>Cancel</Button>:['failed','dead_letter','cancelled'].includes(j.status)&&j.kind!=='deploy'?<Button variant="outline" disabled={busy} onClick={()=>confirm({title:'Retry this job?',description:'A new lease will be issued against the same immutable input. First reconcile any previous external build or model task.',path:`/v2/admin/jobs/${j.id}/action`,method:'POST',body:{action:'retry'},reason:true})}>Retry</Button>:<span className="admin-muted">{j.kind==='deploy'&&j.status==='failed'?'Re-admit from app release':'—'}</span>}</td></tr>)}</tbody></table></div>{!data.jobs.length&&<div className="admin-empty">No worker jobs for visible applications.</div>}</TabsContent>
    <TabsContent value="connections"><PanelTitle title="Work connections" description="These are integration contracts, not live health checks. Never paste credentials into this console."/><div className="admin-connections">{data.connections.map(c=><article className="admin-surface" key={c.id}><div className="admin-card-title"><h3>{c.id.replaceAll('-',' ')}</h3><Status value="Unverified"/></div><p className="admin-muted">{c.state.replaceAll('-',' ')}</p><dl>{Object.entries(c.configuration_present).map(([key,present])=><div key={key}><dt>{key}</dt><dd>{present?'Present · not validated':'Not configured'}</dd></div>)}</dl><h4>Required acceptance test</h4><p>{c.acceptance}</p></article>)}</div></TabsContent>
    <TabsContent value="audit"><PanelTitle title="Audit history" description="Recent visible-app and account/policy events. Source, query results, tokens, and model prompts are excluded."/><div className="admin-boundary"><ScrollText size={20}/><p>{data.pending_audit_delivery} events await external delivery. The local audit database is not tamper-proof; connect the append-only work sink.</p></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>When</th><th>Action</th><th>Actor</th><th>Resource</th></tr></thead><tbody>{data.audit.map(a=><tr key={a.id}><td>{date(a.created)}</td><td>{a.action}</td><td>{a.actor}</td><td className="admin-wrap">{data.apps.find(app=>app.id===a.resource)?.name??a.resource}</td></tr>)}</tbody></table></div>{!data.audit.length&&<div className="admin-empty">No scoped events have been recorded yet.</div>}</TabsContent>
   </div>
  </Tabs>}
  <Dialog open={!!app} onOpenChange={v=>{if(!v)setApp(null)}}><DialogContent className="dc-dialog admin-detail-dialog"><DialogHeader><DialogTitle>{app?.name}</DialogTitle><DialogDescription>Release, review, grants and maintainer actions remain independently authorized.</DialogDescription></DialogHeader>{app&&<HostedPanel appId={app.id} user={user} onChange={async()=>{await refresh();await onChange()}}/>}</DialogContent></Dialog>
  <Dialog open={!!policyApp} onOpenChange={v=>{if(!v)setPolicyApp(null)}}><DialogContent className="dc-dialog"><DialogHeader><DialogTitle>Application lifecycle</DialogTitle><DialogDescription>{policyApp?.name} · Changing policy invalidates current runtime sessions.</DialogDescription></DialogHeader>{policyApp&&<form className="admin-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate(`/v2/apps/${policyApp.id}/lifecycle`,'PUT',{support_contact:f.get('support_contact'),review_due:Date.parse(String(f.get('review_due'))+'T23:59:59Z')/1000,profile:f.get('profile'),queries_per_minute:Number(f.get('queries_per_minute')),min_refresh_seconds:Number(f.get('min_refresh_seconds')),expected_revision:policyApp.lifecycle?.revision??0}))setPolicyApp(null)}}><label>Support contact<Input name="support_contact" required maxLength={200} defaultValue={policyApp.lifecycle?.support_contact??''} placeholder="Accountable team or company support address"/></label><label>Access review due (UTC)<Input type="date" name="review_due" required defaultValue={policyApp.lifecycle?new Date(policyApp.lifecycle.review_due*1000).toISOString().slice(0,10):''}/></label><label>Runtime profile<select aria-label="Runtime profile" name="profile" defaultValue={policyApp.lifecycle?.profile??'custom-backend'}><option value="custom-backend">Custom backend · independent review</option><option value="standard-dashboard">Standard dashboard · verified platform runtime</option></select></label><label>App query requests per minute<Input name="queries_per_minute" type="number" min={1} max={1000} defaultValue={policyApp.lifecycle?.queries_per_minute??120}/></label><label>Minimum refresh interval per user/query (seconds)<Input name="min_refresh_seconds" type="number" min={0} max={3600} defaultValue={policyApp.lifecycle?.min_refresh_seconds??0}/></label><Button disabled={busy} className="primary-button">Save lifecycle policy</Button></form>}{error&&<p className="form-error" role="alert">{error}</p>}</DialogContent></Dialog>
  <Dialog open={!!person} onOpenChange={v=>{if(!v)setPerson(null)}}><DialogContent className="dc-dialog"><DialogHeader><DialogTitle>Edit access: {person?.name}</DialogTitle><DialogDescription>Changes revoke this person’s existing sessions. App sharing still does not grant data access.</DialogDescription></DialogHeader>{person&&<form className="admin-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const body={...person,role:f.get('role'),groups:String(f.get('groups')).split(',').map(v=>v.trim()).filter(Boolean),enabled:f.get('enabled')==='true'};setPerson(null);confirm({title:'Apply account access changes?',description:'Existing sessions for this person will be revoked. Confirm the role and data-group membership are authorized.',path:'/admin/users',method:'PUT',body})}}><label>Workspace role<select aria-label="Workspace role" name="role" defaultValue={person.role}>{['viewer','builder','reviewer','admin'].map(role=><option key={role}>{role}</option>)}</select></label><label>Groups (comma separated)<Input name="groups" defaultValue={person.groups.join(', ')}/></label><label>Account status<select aria-label="Account status" name="enabled" defaultValue={String(Boolean(person.enabled))}><option value="true">Enabled</option><option value="false">Disabled</option></select></label><Button className="primary-button">Review change</Button></form>}</DialogContent></Dialog>
  <Dialog open={newPackage} onOpenChange={setNewPackage}><DialogContent className="dc-dialog"><DialogHeader><DialogTitle>Add exact package rule</DialogTitle><DialogDescription>Use a trusted inventory. New rules start revoked until separately enabled in the policy table.</DialogDescription></DialogHeader><form className="admin-form" onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(await mutate('/v2/runtime-packages','POST',f))setNewPackage(false)}}><label>Ecosystem<select aria-label="Ecosystem" name="ecosystem">{['npm','pypi','os','image'].map(v=><option key={v}>{v}</option>)}</select></label><label>Name<Input name="name" required maxLength={200}/></label><label>Exact version<Input name="version" required maxLength={100}/></label><label>SHA-256 integrity<Input name="integrity" pattern="sha256:[a-f0-9]{64}" required placeholder="sha256:…"/></label><label>Source registry<Input name="source" required maxLength={500}/></label><Button disabled={busy} className="primary-button">Save unapproved rule</Button></form>{error&&<p role="alert" className="form-error">{error}</p>}</DialogContent></Dialog>
  <AlertDialog open={!!confirmation} onOpenChange={v=>{if(!v)setConfirmation(null)}}><AlertDialogContent className="dc-dialog"><AlertDialogHeader><AlertDialogTitle>{confirmation?.title}</AlertDialogTitle><AlertDialogDescription>{confirmation?.description}</AlertDialogDescription></AlertDialogHeader>{confirmation?.reason&&<label>Reason<Input value={reason} minLength={8} maxLength={300} onChange={e=>setReason(e.target.value)} placeholder="Reason for operator intervention"/></label>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep unchanged</AlertDialogCancel><AlertDialogAction disabled={busy||Boolean(confirmation?.reason&&reason.trim().length<8)} onClick={async e=>{e.preventDefault();if(confirmation&&await mutate(confirmation.path,confirmation.method,confirmation.reason?{...(confirmation.body as object),reason}:confirmation.body))setConfirmation(null)}}>Confirm change</AlertDialogAction></AlertDialogFooter>{error&&<p className="form-error" role="alert">{error}</p>}</AlertDialogContent></AlertDialog>
 </section>;
}
function Kpi({label,value,note}:{label:string;value:number;note:string}){return <article className="admin-kpi"><span>{label}</span><strong>{value.toString().padStart(2,'0')}</strong><small>{note}</small></article>}
function PanelTitle({title,description}:{title:string;description:string}){return <div className="admin-panel-title"><h2>{title}</h2><p>{description}</p></div>}
function Status({value}:{value:string}){return <span className={'admin-status '+(['Blocked','Revoked','Disabled','Suspended','failed','dead_letter'].includes(value)?'warning':'')}>{value.replaceAll('_',' ')}</span>}
