import {lazy,Suspense,useEffect,useState} from 'react';
import {Orbit,Upload,Terminal,ArrowUpRight,Bookmark,Pause,Play,LogOut,Workflow,Database} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Toaster,toast} from 'sonner';
const LazySpace=lazy(()=>import('./space'));
function Space({playing}:{playing:boolean}){return <Suspense fallback={null}><LazySpace playing={playing}/></Suspense>}
import {AppPreview} from './app-preview';
import {categories} from './categories';
import {api,download,type Identity} from './api';
import {Login,ReleasePanel,RegistryTools,ExecutePanel} from './platform';

export default function Home(){
 const [user,setUser]=useState<Identity|null>(null),[loading,setLoading]=useState(true),[state,setState]=useState<any>({apps:[],skills:[],queries:[],packages:[]});
 const [tab,setTab]=useState('gallery'),[category,setCategory]=useState('All apps'),[search,setSearch]=useState(''),[saved,setSaved]=useState(false),[motion,setMotion]=useState(false);
 const [selected,setSelected]=useState<string|null>(null),[modal,setModal]=useState(''),[asset,setAsset]=useState<any>(null),[audience,setAudience]=useState('Private'),[permission,setPermission]=useState('run'),[token,setToken]=useState('');
 const active=state.apps.find((a:any)=>a.id===selected);
 async function refresh(){setState(await api('/state'))}
 async function attempt(fn:()=>Promise<void>){try{await fn()}catch(e){toast.error((e as Error).message)}}
 useEffect(()=>{setMotion(!matchMedia('(prefers-reduced-motion: reduce)').matches);api<Identity>('/me').then(async u=>{setUser(u);await refresh();setSelected(new URLSearchParams(location.search).get('app'))}).catch(()=>{}).finally(()=>setLoading(false))},[]);
 async function login(u:Identity){setUser(u);await attempt(refresh)}
 async function review(action:string){await api(`/assets/${asset.kind}/${asset.id}/${asset.version}/review`,'POST',{action});setAsset(null);await refresh();toast.success('Review recorded')}
 const visible=state.apps.filter((a:any)=>(tab!=='mine'||a.mine)&&(category==='All apps'||a.category===category)&&(!saved||a.saved)&&`${a.name} ${a.description}`.toLowerCase().includes(search.toLowerCase()));
 if(loading)return <div className="login-page">Opening your orbit…</div>;
 if(!user)return <><Space playing={motion}/><Login onLogin={login}/></>;
 return <div className="dreamcatcher"><Space playing={motion}/><div className="space-wash"/><Tabs value={tab} onValueChange={setTab} className="site-tabs">
 <header className="site-header"><a href="/" className="brand"><Orbit size={30}/><span>dreamcatcher</span><span className="beta-label">BETA</span></a><TabsList className="main-nav">{['gallery','mine','skills','governance'].map(t=><TabsTrigger key={t} value={t}>{t==='mine'?'My apps':t[0].toUpperCase()+t.slice(1)}</TabsTrigger>)}</TabsList><div className="header-end"><span className="workspace-label">{user.name} · {user.role}</span><Button variant="ghost" size="icon" aria-label="Sign out" onClick={()=>attempt(async()=>{await api('/logout','POST');setUser(null);setToken('')})}><LogOut size={17}/></Button></div></header>
 <main className="main-container"><section className={`hero ${tab!=='gallery'?'compact-hero':''}`}><div className="hero-copy"><div className="eyebrow"><span className="tiny-orbit"/>THE IDEAS THAT MOVE US FORWARD</div><h1>{tab==='skills'?<>Shared skills.<br/><span>New possibilities.</span></>:tab==='governance'?<>Built to share.<br/><span>Ready to trust.</span></>:<>Small tools.<br/><span>Giant leaps.</span></>}</h1><p>Discover the tools your team is building. Make your next idea real.</p></div><div className="hero-actions"><button className="launch-link sdk-link" onClick={()=>setModal('sdk')}><span className="link-icon"><Terminal/></span><span><strong>Download SDK</strong><small>Everything you need to start building</small></span><ArrowUpRight/></button><button className="launch-link upload-link" onClick={()=>setModal('upload')}><span className="link-icon"><Upload/></span><span><strong>Upload your app</strong><small>Start with a link. Give it an orbit.</small></span><ArrowUpRight/></button><div className="hero-note">App access and data access are checked separately.</div></div></section>
 {['gallery','mine'].map(t=><TabsContent value={t} key={t}><div className="gallery-heading"><h2>{t==='mine'?'Your collection':'App gallery'} <span className="count">{visible.length.toString().padStart(2,'0')}</span></h2><span>Built by your team</span></div><div className="gallery-toolbar"><div className="category-filters">{categories.map(c=><Button key={c} variant="ghost" className={category===c?'filter active':'filter'} onClick={()=>setCategory(c)}>{c}</Button>)}</div><div className="gallery-controls"><Input aria-label="Search apps" placeholder="Search apps" value={search} onChange={e=>setSearch(e.target.value)}/><Button variant="outline" size="icon" aria-label="Show saved apps" aria-pressed={saved} onClick={()=>setSaved(!saved)}><Bookmark fill={saved?'currentColor':'none'} size={17}/></Button></div></div><div className="app-grid">{visible.map((a:any)=><article key={a.id} className={`app-card ${a.theme}`}><button className="preview-button" onClick={()=>{setSelected(a.id);setToken('')}} aria-label={`Explore ${a.name}`}><AppPreview kind={a.kind} theme={a.theme}/><span className="preview-open">Explore app <ArrowUpRight size={16}/></span></button><div className="card-body"><div className="card-title"><button onClick={()=>setSelected(a.id)}>{a.name}</button><span className="badge">{a.status}</span></div><p>{a.description}</p><div className="card-bottom"><span className={`avatar ${a.theme}`}>{a.initials}</span><span>{a.owner}</span><Button className="bookmark" variant="ghost" size="icon" aria-label="Save app" onClick={()=>attempt(async()=>{await api(`/apps/${a.id}/favorite`,'POST');await refresh()})}><Bookmark size={16} fill={a.saved?'currentColor':'none'}/></Button></div></div></article>)}</div>{!visible.length&&<div className="gallery-empty">No apps match these filters.</div>}</TabsContent>)}
 <TabsContent value="skills"><div className="section-toolbar"><div><h2>Skill library</h2><p className="section-description">Portable instructions, contracts, and deterministic query workflows.</p></div>{['builder','admin'].includes(user.role)&&<label>Import skill ZIP<Input type="file" accept=".zip" onChange={e=>{const f=e.target.files?.[0];if(f)attempt(async()=>{const form=new FormData();form.append('file',f);await api('/skills/import','POST',form);await refresh();toast.success('Imported for independent review')})}}/></label>}</div><div className="skills-grid">{state.skills.map((s:any)=><button key={s.id+s.version} className="skill-card violet" onClick={()=>setAsset({...s,kind:'skill'})}><div className="skill-top"><Workflow size={28}/><span className="version">v{s.version}</span></div><h3>{s.name}</h3><p>{s.description}</p><div className="skill-meta"><span>{s.status}</span><span>Explore skill <ArrowUpRight size={14}/></span></div></button>)}</div><div className="transfer-banner"><Workflow/><div><h3>Good skills travel.</h3><p>Export a complete ZIP. Credentials never travel with it. Destination approval is always required.</p></div></div></TabsContent>
 <TabsContent value="governance"><h2>Governed queries</h2><div className="readiness-list">{state.queries.map((q:any)=><button key={q.id+q.version} onClick={()=>setAsset({...q,kind:'query'})}><Database size={20}/><span><strong>{q.name} · v{q.version}</strong><small>{q.source} · {q.grain}</small></span><span className="badge">{q.status}</span><ArrowUpRight size={16}/></button>)}</div><h2 className="section-spacer">Package policies</h2><div className="readiness-list">{state.packages.map((p:any)=><div className="check-row" key={p.name+p.version}><code>{p.name}@{p.version}</code><span>{p.approved?'Approved':'Revoked'}</span></div>)}{!state.packages.length&&<p>No package versions approved yet. New releases fail closed for unapproved dependencies.</p>}</div><RegistryTools user={user} onChange={refresh}/></TabsContent>
 <footer className="site-footer"><div><Orbit size={17}/><span>Built for the people building what’s next.</span></div><div><span>{user.demo?'Local demo · Synthetic data':'Workspace registry'}</span><button onClick={()=>setMotion(!motion)}>{motion?<Pause size={13}/>:<Play size={13}/>} Motion {motion?'on':'off'}</button></div></footer></main></Tabs>
 <Sheet open={!!active} onOpenChange={o=>{if(!o){setSelected(null);setToken('')}}}><SheetContent className="detail-sheet">{active&&<><div className="detail-preview"><AppPreview kind={active.kind} theme={active.theme} large/></div><SheetHeader><SheetTitle>{active.name}</SheetTitle><SheetDescription>{active.description}</SheetDescription></SheetHeader><div className="detail-actions">{active.url?<Button asChild className="primary-button"><a href={active.url} target="_blank" rel="noopener noreferrer">Open external app <ArrowUpRight size={15}/></a></Button>:<span className="badge">Built-in demo</span>}{(active.mine||user.role==='admin')&&<Button variant="outline" onClick={()=>{setAudience('Private');setModal('share')}}>Sharing</Button>}</div><div className="detail-body"><p className="muted">{active.audience} · {active.status} · v{active.version}</p><Tabs defaultValue="run"><TabsList><TabsTrigger value="run">Queries</TabsTrigger><TabsTrigger value="skills">Skills</TabsTrigger><TabsTrigger value="release">Release</TabsTrigger><TabsTrigger value="sdk">SDK token</TabsTrigger></TabsList><TabsContent value="run"><ExecutePanel key={active.id} appId={active.id} references={active.queryRefs||[]}/></TabsContent><TabsContent value="skills"><ExecutePanel key={active.id+'skill'} appId={active.id} references={active.skillRefs||[]} skill/></TabsContent><TabsContent value="release"><ReleasePanel appId={active.id} user={user} onChange={refresh}/></TabsContent><TabsContent value="sdk"><p>One-hour token bound to this app and your current permissions. Copy once into your app’s server-side environment. Never commit it.</p><Button onClick={()=>attempt(async()=>{const result=await api('/tokens','POST',{app_id:active.id});setToken(result.token)})}>Create SDK token</Button>{token&&<pre className="result-json">{token}</pre>}<Button variant="outline" onClick={()=>attempt(async()=>{await api('/tokens/revoke-all','POST');setToken('');toast.success('Your SDK tokens were revoked')})}>Revoke my SDK tokens</Button></TabsContent></Tabs></div></>}</SheetContent></Sheet>
 <Dialog open={!!modal} onOpenChange={o=>{if(!o)setModal('')}}><DialogContent className="dc-dialog"><DialogHeader><DialogTitle>{modal==='upload'?'Give your app an orbit.':modal==='sdk'?'Your idea. Our launchpad.':'Share this release'}</DialogTitle><DialogDescription>{modal==='upload'?'Register a URL as a private draft. Code is not uploaded or executed.':modal==='sdk'?'Typed identity, governed queries, and portable skills.':'Sharing does not grant data access. Saving replaces existing grants.'}</DialogDescription></DialogHeader>
 {modal==='upload'&&<form className="upload-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);attempt(async()=>{await api('/apps','POST',Object.fromEntries(f));await refresh();setModal('');setTab('mine');toast.success('Private draft saved')})}}><label>App URL<Input name="url" type="url" required placeholder="https://your-app.company.com"/></label><label>Name<Input name="name" required maxLength={70}/></label><label>Description<Textarea name="description" required maxLength={300}/></label><label>Category<select name="category">{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><Button className="primary-button">Add to my apps</Button></form>}
 {modal==='sdk'&&<><div className="code-window"><pre>{`import { createDreamcatcher } from '@dreamcatcher/sdk';\nconst dc = createDreamcatcher({\n  baseUrl: 'http://localhost:8000',\n  appId: 'build-readiness',\n  getToken: () => process.env.DC_TOKEN\n});\nawait dc.queries.run('assembly-readiness@1.0.0', {\n  program_id: 'terran-r'\n});`}</pre></div><Button className="primary-button" onClick={()=>attempt(()=>download('/sdk/download','dreamcatcher-sdk.tgz'))}>Download SDK package</Button><p className="form-footnote">Install with npm install ./dreamcatcher-sdk.tgz. Create an app-bound token in app details. Corporate credentials stay on the registry server.</p></>}
 {modal==='share'&&<><label>Audience<select value={audience} onChange={e=>setAudience(e.target.value)}>{['Private','Workspace',...categories.slice(1)].map(c=><option key={c}>{c}</option>)}</select></label><label>Permission<select value={permission} onChange={e=>setPermission(e.target.value)}><option value="run">Run app</option><option value="edit">Edit app</option></select></label><Button className="primary-button" onClick={()=>attempt(async()=>{await api(`/apps/${active.id}/sharing`,'PUT',{grants:audience==='Private'?[]:[{subject:audience==='Workspace'?'workspace':'group:'+audience,permission}]});await refresh();setModal('');toast.success('Sharing updated')})}>Save sharing</Button><Button variant="outline" onClick={()=>attempt(async()=>{await navigator.clipboard.writeText(location.origin+'/?app='+active.id);toast.success('Link copied; recipients still need permission')})}>Copy app link</Button><p className="form-footnote">Only published releases can be shared. Choose Private to remove all grants.</p></>}
 </DialogContent></Dialog>
 <Dialog open={!!asset} onOpenChange={o=>{if(!o)setAsset(null)}}><DialogContent className="dc-dialog management-dialog">{asset&&<><DialogHeader><DialogTitle>{asset.name}</DialogTitle><DialogDescription>{asset.id}@{asset.version} · {asset.status}</DialogDescription></DialogHeader><pre className="result-json">{asset.kind==='query'?asset.sql:JSON.stringify({runtime:asset.runtime,queries:asset.queries,steps:asset.steps,tools:asset.tools},null,2)}</pre><p>Allowed groups: {asset.allowed_groups?.join(', ')}</p>{asset.kind==='skill'&&<Button variant="outline" onClick={()=>attempt(()=>download(`/skills/${asset.id}/${asset.version}/export`,`${asset.id}-${asset.version}.zip`))}>Export portable ZIP</Button>}{['reviewer','admin'].includes(user.role)&&<div className="share-actions"><Button onClick={()=>attempt(()=>review('approve'))}>Approve version</Button><Button variant="outline" onClick={()=>attempt(()=>review('revoke'))}>Revoke version</Button></div>}<p className="form-footnote">Versions are immutable. A different reviewer must approve new assets; imports do not inherit trust.</p></>}</DialogContent></Dialog>
 <Toaster theme="dark" position="bottom-right" richColors/></div>
}
