import {useEffect,useState} from 'react';
import {Orbit,LogOut,Plus,Upload,Download,ShieldCheck,ArrowRight,KeyRound} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api,type Identity} from './api';
import {toast} from 'sonner';

export function Login({onLogin}:{onLogin:(u:Identity)=>void}){
 const [error,setError]=useState(''),[health,setHealth]=useState<any>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/health').then(setHealth).catch(e=>setError(e.message))},[]);
 return <main className="login-page"><div className="login-card"><Orbit size={40}/><h1>dreamcatcher</h1><p>Your team’s tools. One shared orbit.</p>{health?.auth_mode==='oidc'?<a className="sso-button" href="/auth/login">Continue with company SSO <ArrowRight size={16}/></a>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{onLogin(await api('/login','POST',{email:f.get('email'),password:f.get('password')}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Email<Input name="email" type="email" required defaultValue={health?.demo?'builder@demo.local':''}/></label><label>Password<Input name="password" type="password" required autoComplete="current-password"/></label><Button className="primary-button full-width" disabled={busy}>{busy?'Signing in…':'Enter your workspace'}<ArrowRight size={16}/></Button></form>}{error&&<p className="form-error" role="alert">{error}</p>}{health?.demo&&<div className="demo-login"><strong>Local demo environment</strong><p>Accounts: builder, reviewer, admin, viewer, outsider @demo.local</p><p>Default password: <code>Dreamcatcher-local-1!</code></p><p>Use builder to create; reviewer to approve. No company systems are connected.</p></div>}</div></main>
}

export function ReleasePanel({appId,onChange,user}:{appId:string;onChange:()=>Promise<void>;user:Identity}){
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[open,setOpen]=useState(false),[body,setBody]=useState(JSON.stringify({version:'1.0.0',queries:[],skills:[],lockfile:{lockfileVersion:3,packages:{'':{name:'my-app',version:'1.0.0'}}}},null,2));
 const refresh=()=>api<any[]>('/apps/'+appId+'/releases').then(setRows).catch(e=>setError(e.message));
 useEffect(()=>{refresh()},[appId]);
 async function action(path:string){try{await api(path,'POST');await refresh();await onChange();toast.success('Release updated')}catch(e){setError((e as Error).message)}}
 return <div className="release-panel"><Button variant="outline" onClick={()=>setOpen(true)}><Plus size={15}/> Add release manifest</Button>{error&&<p className="form-error">{error}</p>}{rows.map(r=><article className="release-record" key={r.version}><div><strong>v{r.version}</strong><span>{r.status}</span></div><code>{r.digest.slice(0,20)}…</code>{r.findings.map((f:any,i:number)=><p key={i} className="finding"><strong>{f.gate}</strong> {typeof f.message==='string'?f.message:JSON.stringify(f.message)}{f.items&&': '+f.items.join(', ')}</p>)}<div className="release-buttons">{r.status==='pending'&&<label className="upload-evidence">Attach build evidence<Input type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{await api(`/apps/${appId}/releases/${r.version}/evidence`,'POST',JSON.parse(await f.text()));await refresh();toast.success('Evidence validated')}catch(e){setError((e as Error).message)}}}/></label>}{['reviewer','admin'].includes(user.role)&&<Button variant="outline" onClick={()=>action(`/apps/${appId}/releases/${r.version}/approve`)}>Approve</Button>}<Button disabled={r.status!=='approved'} className="primary-button" onClick={()=>action(`/apps/${appId}/publish/${r.version}`)}>Publish / restore</Button></div></article>)}<Button variant="outline" onClick={()=>action('/apps/'+appId+'/unpublish')}>Unpublish and revoke sharing</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="dc-dialog"><DialogHeader><DialogTitle>Register a release</DialogTitle><DialogDescription>Paste the complete manifest, including package-lock content. A new version is immutable.</DialogDescription></DialogHeader><Textarea className="json-editor" value={body} onChange={e=>setBody(e.target.value)}/><Button className="primary-button" onClick={async()=>{try{await api('/apps/'+appId+'/releases','POST',JSON.parse(body));setOpen(false);await refresh();toast.success('Release registered')}catch(e){setError((e as Error).message)}}}>Create version</Button></DialogContent></Dialog></div>
}

const queryExample={id:'my-governed-query',version:'1.0.0',name:'My governed query',description:'Describe business intent',connector:'sqlite',sources:['assembly_readiness'],sql:'SELECT assembly_id, system_name, readiness_pct FROM assembly_readiness WHERE program_id = @program_id AND authorized_user = @_user_id',grain:'One row per assembly',parameters:{program_id:'string'},allowed_groups:['Manufacturing']};
export function RegistryTools({user,onChange}:{user:Identity;onChange:()=>Promise<void>}){
 const [mode,setMode]=useState(''),[text,setText]=useState(''),[error,setError]=useState(''),[audit,setAudit]=useState<any[]>([]),[accounts,setAccounts]=useState<any[]>([]);
 function start(m:string,value:unknown){setMode(m);setText(JSON.stringify(value,null,2));setError('')}
 async function save(){try{await api(mode==='query'?'/queries':mode==='package'?'/packages':'/admin/users',mode==='query'?'POST':'PUT',JSON.parse(text));await onChange();setMode('');toast.success('Registry updated')}catch(e){setError((e as Error).message)}}
 return <section className="registry-tools"><div><h3>Workspace controls</h3><p>Changes are enforced by the server and recorded in the audit log.</p></div><div className="registry-actions">{['builder','admin'].includes(user.role)&&<Button variant="outline" onClick={()=>start('query',queryExample)}><Plus size={15}/> Register query</Button>}{user.role==='admin'&&<><Button variant="outline" onClick={()=>start('package',{name:'zod',version:'3.25.76',integrity:'COPY_EXACT_SHA512_FROM_LOCKFILE',source:'https://registry.npmjs.org/zod/-/zod-3.25.76.tgz',approved:true})}>Package policy</Button><Button variant="outline" onClick={async()=>{try{setAccounts(await api('/admin/users'));setMode('accounts')}catch(e){toast.error((e as Error).message)}}}>People & groups</Button></>}{['admin','reviewer'].includes(user.role)&&<Button variant="outline" onClick={async()=>{try{setAudit(await api('/audit'));setMode('audit')}catch(e){toast.error((e as Error).message)}}}>Audit history</Button>}</div><Dialog open={!!mode} onOpenChange={o=>{if(!o)setMode('')}}><DialogContent className="dc-dialog management-dialog"><DialogHeader><DialogTitle>{mode==='query'?'Register governed query':mode==='package'?'Set exact-version package policy':mode==='audit'?'Audit history':mode==='accounts'?'People & groups':'Account settings'}</DialogTitle><DialogDescription>{mode==='query'?'New versions start pending and require a different reviewer.':mode==='package'?'Integrity and registry URL must match. Set approved to false to revoke.':'Server-side workspace records.'}</DialogDescription></DialogHeader>{mode==='audit'?<div className="audit-list">{audit.map(a=><div key={a.id}><strong>{a.action}</strong><span>{a.actor} · {a.resource}</span><small>{new Date(a.created*1000).toLocaleString()}</small></div>)}</div>:mode==='accounts'?<div className="audit-list">{accounts.map(a=><button key={a.id} onClick={()=>start('account',{id:a.id,email:a.email,name:a.name,role:a.role,groups:a.groups,enabled:a.enabled})}><strong>{a.name}</strong><span>{a.role} · {a.groups.join(', ')}</span></button>)}<Button onClick={()=>start('account',{id:'new-user',email:'new-user@example.com',name:'New user',role:'viewer',groups:[],enabled:true,password:'REPLACE_WITH_14_CHAR_PASSWORD'})}>Add account</Button></div>:<><Textarea className="json-editor" value={text} onChange={e=>setText(e.target.value)}/><Button className="primary-button" onClick={save}>Save</Button></>}{error&&<p className="form-error">{error}</p>}</DialogContent></Dialog></section>
}

export function ExecutePanel({appId,references,skill=false}:{appId:string;references:string[];skill?:boolean}){
 const [params,setParams]=useState('{"program_id":"terran-r"}'),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ref,setRef]=useState(references[0]||'');
 return <div className="execute-panel"><label>Approved reference<select value={ref} onChange={e=>setRef(e.target.value)}>{references.map(r=><option key={r}>{r}</option>)}</select></label><label>Parameters<Textarea value={params} onChange={e=>setParams(e.target.value)}/></label><Button className="primary-button" disabled={!ref||busy} onClick={async()=>{setBusy(true);setError('');try{setResult(await api('/execute/'+(skill?'skill':'query'),'POST',{app_id:appId,reference:ref,parameters:JSON.parse(params)}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Running…':skill?'Run governed skill':'Run governed query'}</Button>{error&&<p className="form-error" role="alert">{error}</p>}{result&&<pre className="result-json">{JSON.stringify(result,null,2)}</pre>}</div>
}
